### ISSUE TITLE
Проблемы с  кодировкой ANSI и поддержкой русских операторов

### ISSUE THREAD

**Issue by thabru** [prospero78/Oberon07ru#1]
1. Файл samples/windows/HW.ob07 - при попытке открыть редактором прилагаемым editor.exe - выскакивает сообщение об ошибке.
После того как пример был набран вручную и сохранен. компиляция прошла успешно.
2. При попытке заменить оператор IMPORT на  ИМПОРТ (UTF + ANSI) появляется сообщение об ошибке
"18-27 - неожиданный конец файла".
3. При попытке заменить строку на Out.String("Привет Мир!"); с русским текстом 
файл компилируется, но при запуске скомпилированного HW.exe вместо русского текста появляется псевдографика
4. При попытке открыть файл который был исправлен и сохранён в Notepad++  появляется сообщение о неправильном формате файла

Проверялось на Windows7 * 64 rus

Заготовка статьи на  ТХАБ.рф про Oberon07ru - https://тхаб.рф/wiki/Oberon07ru

**Comment by prospero78** [comment]
Прилагаемый редактор открывает файлы в кодировке UTF8. Русификация компилятора работает только с CP866(DOS).
Компилировать пример только из командной строки.
Кодировка консоли должна быть установлена в CP866 (настраивается бат-файлом, например. при сборке компилятора -- можно взять как пример)

**Comment by prospero78** [comment]
Переделал под кодировку cp1251 исходники. но за редактор пока не брался)
